# -*- coding: utf-8 -*-
"""U5_Calculus_for_ML_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g56lxXir__FU1K6hEUobTNiYFDyFmPY0
"""

import numpy as np
import sympy as sp

x, y = sp.symbols('x y')
sp.init_printing()
np.random.seed(42)
print('Setup complete. SymPy', sp.__version__, '| NumPy', np.__version__)

def f(x):
    return x**2

h = 1e-6
slope_at_3 = (f(3 + h) - f(3)) / h
print('Numerical f\'(3):', round(slope_at_3, 4), ' (exact = 6)')

expr = x**2
deriv = sp.diff(expr, x)
print('d/dx (x**2) =', deriv)

print('Symbolic f\'(3) =', deriv.subs(x, 3))

def g(x):
    return x**3 + 2*x

f2 = x**2 + 3*x*y + y**2

print('df/dx =', sp.diff(f2, x))
print('df/dy =', sp.diff(f2, y))

grad = [sp.diff(f2, v) for v in (x, y)]
print('grad f =', grad)


grad_at = [g.subs({x: 1, y: 2}) for g in grad]
print('grad f at (1, 2) =', grad_at)

h2 = x**2 * y + sp.sin(y)

by_hand = sp.cos(x**2) * 2*x
by_sympy = sp.diff(sp.sin(x**2), x)

print('By hand :', by_hand)
print('By SymPy:', by_sympy)
print('Match?  ', sp.simplify(by_hand - by_sympy) == 0)

expr3 = (3*x + 1)**4
print('d/dx (3x+1)^4 =', sp.diff(expr3, x))

X = np.random.randn(4, 3)
Y = np.random.randn(4, 1)
W1 = np.random.randn(3, 5) * 0.1
W2 = np.random.randn(5, 1) * 0.1

z1 = X @ W1
h  = np.maximum(0, z1)
y_hat = h @ W2
loss = ((y_hat - Y) ** 2).mean()
print('Initial loss:', round(loss, 4))

dy   = 2 * (y_hat - Y) / Y.size
dW2  = h.T @ dy
dh   = dy @ W2.T
dz1  = dh * (z1 > 0)
dW1  = X.T @ dz1

print('dW1 shape:', dW1.shape, '(matches W1)')
print('dW2 shape:', dW2.shape, '(matches W2)')

lr = 0.1
W1 -= lr * dW1
W2 -= lr * dW2

h_new = np.maximum(0, X @ W1)
loss_new = ((h_new @ W2 - Y) ** 2).mean()
print('Loss before:', round(loss, 4))
print('Loss after :', round(loss_new, 4), '-> should be lower')

Xb = np.random.randn(6, 4)
Yb = np.random.randn(6, 1)
Wa = np.random.randn(4, 8) * 0.1
Wb = np.random.randn(8, 1) * 0.1

f5 = x**2 + 3*x*y + y**2
H = sp.hessian(f5, (x, y))
print('Hessian of f:')
sp.pprint(H)

xv = 0.0
lr = 0.2
for step in range(15):
    grad = 2 * (xv - 4)
    xv = xv - lr * grad
print('Converged x:', round(xv, 3), ' (true minimum = 4)')