# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qdwq3tp1J1t5dv26pmey3QzinwF_4Oky
"""



print(2+3)

"""input and output"""

print(4*5)

"""input output by formatting functions (fstring format %formatted"""

print(9%3)

"""fstring

"""

name="varshini"
age=17
print(f"the name is {name} and {age} years older")

"""format string"""



print("The {1} is a {0}".format("cat","animal"))

"""% format"""

name="varshini"
age=21
print("My name is %s and age %d"% (name,age))



print("Welcome to python")

print(50)
print(25)

name="Rahul"
print(name)

a=10
b=20
print()

a=20
b=15
print()
print()

name="anjali"
age=12
print(name,age)

name="priya"
print(f"MY name is {name}")

print("{} is very beautiful city".format("hyderabad"))

name="kiran"
print("My name is %s" %(name))

value=15.7777
print(type(value))

name="Asha"
marks=92
print(f"my name is {name} and i have got {marks} marks ")

print("python","programming","launguage")

name="varsha"
print(name*3)

x=19
y=20
print(f"X value {x} and Y value {y}")

"""defining a basic fuctons"""

def greet():
    print("Hello! Welcome to Python Functions.")
greet()

"""function with parameters"""

def greet_user(name):
    print(f"Hello, {name}!")
greet_user("Alice")
greet_user("Bob")

"""function with default parameters"""

def greet_user(name="Guest"):
    print(f"Welcome, {name}!")
greet_user()
greet_user("Ravi")

""" USING *args (VARIABLE NUMBER OF POSITIONAL ARGUMENTS)"""

def print_names(*names):
    print("Names passed:", names)
    for name in names:
        print("Hello", name)
print_names("Alice", "bob", "Charlie")

"""USING **kwargs

"""

def print_info(**info):
  print(":User info:")
  for key,value in info.items():
    print(f"{key}={value}")
print_info(name="Alice",Age=32,city="patna")

"""combinig ags and kwargs"""

def show_details(*args, **kwargs):
    print("Args:", args)
    print("Kwargs:", kwargs)
show_details(1, 2, 3, name="Rama", city="Delhi")

""" FUNCTION NESTING (CALL ONE FUNCTION INSIDE ANOTHER)

"""

def multiply(a, b):
    return a * b
def square(n):
    return multiply(n, n)
print("Square of 7:", square(7))

"""lambda"""

num=[1,2,3,4,5]
print(list(map(lambda a:a**2,num)))
print(list(filter(lambda a:a%2==0,num)))

from functools import reduce
num=[4,5,6,7,8]
square=list(map(lambda a:a**2,num))
print(square)
total=reduce(lambda x,y:x+y,square)
print(total)

fruits = ['apple', 'banana', 'cherry', 'apple']
print("Original list:", fruits)
print("First fruit:", fruits[2])

fruits.append('orange')
print("After appending:", fruits)