# -*- coding: utf-8 -*-
"""libraries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wmHZTmFgvIBJGob_RvWqW5OMgQE7kLfV
"""

import os
print("Current Directory:", os.getcwd())
print("Files and Folders:", os.listdir())
os.mkdir("demo_folder")
os.rename("demo_folder", "renamed_folder")
os.rmdir("renamed_folder")

from datetime import datetime, date, timedelta
now = datetime.now()
print("Now:", now)
today = date.today()
print("Today's Date:", today)
dob = date(2000, 1, 1)
print("DOB:", dob)
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Tomorrow:", tomorrow)
formatted = now.strftime("%d-%m-%Y %H:%M:%S")
print("Formatted DateTime:", formatted)

import random
print("Random Int:", random.randint(1, 100))

print("Random Float:", random.random())
colors = ['red', 'green', 'blue']
print("Random Color:", random.choice(colors))
random.shuffle(colors)
print("Shuffled List:", colors)
print("Sample:", random.sample(range(1, 50), 5))

from collections import Counter
fruits = ['apple', 'banana', 'apple', 'orange', 'banana', 'apple']
count = Counter(fruits)
print("Fruit Count:", count)

from collections import defaultdict
marks = defaultdict(lambda: 0)
marks['Math'] = 90
marks['Science'] = 80
print("English Marks (not set):", marks['English'])

from collections import namedtuple
Point = namedtuple('Point', 'x y')
p1 = Point(10, 20)
print("Point:", p1)
print("x:", p1.x, "y:", p1.y)

