# -*- coding: utf-8 -*-
"""pandas_week4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PWtd25cp2xrWGIaUHVO-s2wzwSlJS_G
"""

s=pd.Series([1,2,3,4],index=['a','b','c','d'])
print(s)

import pandas as pd
import numpy as np
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print("\nSeries:")
print(s)
data={
    'Name':['varsha','vaishu','gouri','janu'],
    'Age':[19,19,30,22],
    'Salary':[100000,500000,60000,40000]

}
df=pd.DataFrame(data)
print(df)

import pandas as pd
import numpy as np

array=np.array([[1,2,3],[4,5,6],[7,8,9]])
df_from_array=pd.DataFrame(array,columns=['Column1','Column2','Column3'])
print(df_from_array)

array=np.array([[1,2],[3,4],[4,5]])
df_from_array=pd.DataFrame(array,columns=['Column1','Column2'])
print(df_from_array)

print(df[df['Age']>=19])

print(df.loc[1])

print(df.loc[3])

print(df.iloc[0:2])

print(df.iloc[0])

print(df['Name'])

print(df[['Name','Age']])

data_dirty={
    'Name': ['varsha', 'madhu', None, 'janu'],
    'Age': [19, None, 27, 22],
    'Salary': [50000, 60000, None, 80000]
}
df_dirty = pd.DataFrame(data_dirty)
print("\nOriginal Dirty DataFrame:")
print(df_dirty)

print(df_dirty.dropna())
print(df_dirty.fillna({'Name': 'Unknown', 'Age': df_dirty['Age'].mean(), 'Salary': 0}))

print(df_dirty.isnull())

df['Bonus'] = df['Salary']
print(df)
df_renamed = df.rename(columns={'Salary': 'BaseSalary'})
print(df_renamed)
print(df.sort_values(by='Age', ascending=False))
df['AgeGroup'] = df['Age'] > 20
print(df.groupby('AgeGroup')['Salary'].mean())

df_renamed = df.rename(columns={'Salary': 'BaseSalary'})
print(df_renamed)

print(df.sort_values(by='Age', ascending=False))

np.random.seed(1)
num_rows = 10
df_synth = pd.DataFrame({
    'ID': np.arange(1, num_rows + 1),
    'Score': np.random.randint(50, 100, size=num_rows),
    'Passed': np.random.choice([True, False], size=num_rows)
})
print("\nSynthetic DataFrame:")
print(df_synth)

print(df_synth[df_synth['Passed'] == True])

print(df_synth[df_synth['Passed'] == False]['Score'].mean())