# -*- coding: utf-8 -*-
"""week 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEah5Ddld4ZBZu673a4HvO5UoYAD7j3a
"""

try:
  x=int(input("enter a number "))
  print("You entered:",x)
except ValueError:
    print("That is invalid number")

try:
  num=int(input("enter a number to divide 100:"))
  result=100/num
except ZeroDivisionError:
  print("Cannot divide by zero")
except ValueError:
  print("invalid input")
else:
  print("Result is:",result)
finally:
  print("Execution complete.This block always nums")

try:
  a=int("ten")
  b=10/0
except (ValueError, ZeroDivisionError) as e:
  print("An error occurred:" ,e)

def check_age(age):
  if age<=18:
     raise ValueError("age is not eligible to vote")
  else:
    print("age is eligible")
try:
  check_age(14)
  check_age(20)
except ValueError as e:
  print("caught an exception:",e)

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}


# --- Task 1: Python Fundamentals, Lists, Tuples, Sets, Dictionaries, Indexing & Slicing ---
print("\n--- Task 1: Data Generation and Basic Structures ---")

# 1.1 Generate a list of 100 simulated sensor readings.
#    Each reading should be a tuple: (timestamp_str, device_id, device_type, location, value).
#    - timestamp_str: Format as 'YYYY-MM-DD HH:MM:SS'
#    - device_id: A unique ID for each reading (e.g., 'DEV001', 'DEV002', etc., up to 100 unique IDs).
#    - device_type: Randomly chosen from DEVICE_TYPES.
#    - location: Randomly chosen from LOCATIONS.
#    - value: Random float within READING_RANGES for its device_type (round to 2 decimal places).
# Store these in a list called 'raw_sensor_data'.

# Your code for Task 1.1 here:

raw_sensor_data = []

for i in range(1, 101):
    timestamp_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    device_id = f"DEV{i:03d}"

    device_type = random.choice(DEVICE_TYPES)

    location = random.choice(LOCATIONS)

    low, high = READING_RANGES[device_type]
    value = round(random.uniform(low, high), 2)

    raw_sensor_data.append((timestamp_str, device_id, device_type, location, value))

print(raw_sensor_data[:100])

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
raw_sensor_data = []

for i in range(1, 101):
    timestamp_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    device_id = f"DEV{i:03d}"

    device_type = random.choice(DEVICE_TYPES)

    location = random.choice(LOCATIONS)

    low, high = READING_RANGES[device_type]
    value = round(random.uniform(low, high), 2)

    raw_sensor_data.append((timestamp_str, device_id, device_type, location, value))


# 1.2 From 'raw_sensor_data', create a list named 'temperature_readings' containing only the readings
#     where 'device_type' is 'Temperature_Sensor'.
#     Each item in 'temperature_readings' should be a dictionary with keys:
#     'timestamp', 'device_id', 'location', 'temperature_celsius'.
# 1.2 Create a list of temperature sensor readings

temperature_readings = []

for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    if device_type == "Temperature_Sensor":
        temp_dict = {
            "timestamp": timestamp,
            "device_id": device_id,
            "location": location,
            "temperature_celsius": value
        }
        temperature_readings.append(temp_dict)

print("\nTemperature Readings:")
for temp in temperature_readings:
    print(temp)

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
raw_sensor_data = []

for i in range(1, 101):
    timestamp_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    device_id = f"DEV{i:03d}"

    device_type = random.choice(DEVICE_TYPES)

    location = random.choice(LOCATIONS)

    low, high = READING_RANGES[device_type]
    value = round(random.uniform(low, high), 2)

    raw_sensor_data.append((timestamp_str, device_id, device_type, location, value))


# 1.2 From 'raw_sensor_data', create a list named 'temperature_readings' containing only the readings
#     where 'device_type' is 'Temperature_Sensor'.
#     Each item in 'temperature_readings' should be a dictionary with keys:
#     'timestamp', 'device_id', 'location', 'temperature_celsius'.
# 1.2 Create a list of temperature sensor readings

temperature_readings = []

for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    if device_type == "Temperature_Sensor":
        temp_dict = {
            "timestamp": timestamp,
            "device_id": device_id,
            "location": location,
            "temperature_celsius": value
        }
        temperature_readings.append(temp_dict)

print("\nTemperature Readings:")
for temp in temperature_readings:
    print(temp)
 #1.3 Create a set named 'unique_locations' containing all unique locations from 'raw_sensor_data'.

# Your code for Task 1.3 here:



# 1.3 Create a set named 'unique_locations' containing all unique locations

unique_locations = set()

for reading in raw_sensor_data:
    unique_locations.add(reading[3])   # reading[3] is the location

print("\nUnique Locations:")
print(unique_locations)

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
raw_sensor_data = []

for i in range(1, 101):
    timestamp_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    device_id = f"DEV{i:03d}"

    device_type = random.choice(DEVICE_TYPES)

    location = random.choice(LOCATIONS)

    low, high = READING_RANGES[device_type]
    value = round(random.uniform(low, high), 2)

    raw_sensor_data.append((timestamp_str, device_id, device_type, location, value))


# 1.2 From 'raw_sensor_data', create a list named 'temperature_readings' containing only the readings
#     where 'device_type' is 'Temperature_Sensor'.
#     Each item in 'temperature_readings' should be a dictionary with keys:
#     'timestamp', 'device_id', 'location', 'temperature_celsius'.
# 1.2 Create a list of temperature sensor readings

temperature_readings = []

for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    if device_type == "Temperature_Sensor":
        temp_dict = {
            "timestamp": timestamp,
            "device_id": device_id,
            "location": location,
            "temperature_celsius": value
        }
        temperature_readings.append(temp_dict)

print("\nTemperature Readings:")
for temp in temperature_readings:
    print(temp)
 #1.3 Create a set named 'unique_locations' containing all unique locations from 'raw_sensor_data'.

# Your code for Task 1.3 here:



# 1.3 Create a set named 'unique_locations' containing all unique locations

unique_locations = set()

for reading in raw_sensor_data:
    unique_locations.add(reading[3])   # reading[3] is the location

print("\nUnique Locations:")
print(unique_locations)
 #1.4 Create a dictionary named 'device_stats' where keys are 'device_type' and values are
#     a tuple: (min_value, max_value) observed for that device type across all readings.
#     Initialize with sensible large/small values.

# Your code for Task 1.4 here:
# 1.4 Create a dictionary named 'device_stats'

device_stats = {}

# Initialize min and max values
for device in DEVICE_TYPES:
    device_stats[device] = (float('inf'), float('-inf'))

# Update min and max values
for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    min_value, max_value = device_stats[device_type]

    if value < min_value:
        min_value = value

    if value > max_value:
        max_value = value

    device_stats[device_type] = (min_value, max_value)

print("\nDevice Statistics:")
for device, stats in device_stats.items():
    print(device, ":", stats)

# 1.5.1 List Slicing

# Extract elements from 10th to 20th (inclusive)
# Python indexing starts from 0, so 10th element = index 9 and 20th element = index 19
sliced_readings_1 = raw_sensor_data[9:20]

# Extract every 5th reading starting from the beginning
sliced_readings_2 = raw_sensor_data[::5]

print("\nReadings from 10th to 20th:")
for reading in sliced_readings_1:
    print(reading)

print("\nEvery 5th Reading:")
for reading in sliced_readings_2:
    print(reading)

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
raw_sensor_data = []

for i in range(1, 101):
    timestamp_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    device_id = f"DEV{i:03d}"

    device_type = random.choice(DEVICE_TYPES)

    location = random.choice(LOCATIONS)

    low, high = READING_RANGES[device_type]
    value = round(random.uniform(low, high), 2)

    raw_sensor_data.append((timestamp_str, device_id, device_type, location, value))


# 1.2 From 'raw_sensor_data', create a list named 'temperature_readings' containing only the readings
#     where 'device_type' is 'Temperature_Sensor'.
#     Each item in 'temperature_readings' should be a dictionary with keys:
#     'timestamp', 'device_id', 'location', 'temperature_celsius'.
# 1.2 Create a list of temperature sensor readings

temperature_readings = []

for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    if device_type == "Temperature_Sensor":
        temp_dict = {
            "timestamp": timestamp,
            "device_id": device_id,
            "location": location,
            "temperature_celsius": value
        }
        temperature_readings.append(temp_dict)

print("\nTemperature Readings:")
for temp in temperature_readings:
    print(temp)
 #1.3 Create a set named 'unique_locations' containing all unique locations from 'raw_sensor_data'.

# Your code for Task 1.3 here:



# 1.3 Create a set named 'unique_locations' containing all unique locations

unique_locations = set()

for reading in raw_sensor_data:
    unique_locations.add(reading[3])   # reading[3] is the location

print("\nUnique Locations:")
print(unique_locations)
 #1.4 Create a dictionary named 'device_stats' where keys are 'device_type' and values are
#     a tuple: (min_value, max_value) observed for that device type across all readings.
#     Initialize with sensible large/small values.

# Your code for Task 1.4 here:
# 1.4 Create a dictionary named 'device_stats'

device_stats = {}

# Initialize min and max values
for device in DEVICE_TYPES:
    device_stats[device] = (float('inf'), float('-inf'))

# Update min and max values
for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    min_value, max_value = device_stats[device_type]

    if value < min_value:
        min_value = value

    if value > max_value:
        max_value = value

    device_stats[device_type] = (min_value, max_value)

print("\nDevice Statistics:")
for device, stats in device_stats.items():
    print(device, ":", stats)
# 1.5.1 List Slicing

# Extract elements from 10th to 20th (inclusive)
# Python indexing starts from 0, so 10th element = index 9 and 20th element = index 19
sliced_readings_1 = raw_sensor_data[9:20]

# Extract every 5th reading starting from the beginning
sliced_readings_2 = raw_sensor_data[::5]

print("\nReadings from 10th to 20th:")
for reading in sliced_readings_1:
    print(reading)

print("\nEvery 5th Reading:")
for reading in sliced_readings_2:
    print(reading)

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
raw_sensor_data = []

for i in range(1, 101):
    timestamp_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    device_id = f"DEV{i:03d}"

    device_type = random.choice(DEVICE_TYPES)

    location = random.choice(LOCATIONS)

    low, high = READING_RANGES[device_type]
    value = round(random.uniform(low, high), 2)

    raw_sensor_data.append((timestamp_str, device_id, device_type, location, value))


# 1.2 From 'raw_sensor_data', create a list named 'temperature_readings' containing only the readings
#     where 'device_type' is 'Temperature_Sensor'.
#     Each item in 'temperature_readings' should be a dictionary with keys:
#     'timestamp', 'device_id', 'location', 'temperature_celsius'.
# 1.2 Create a list of temperature sensor readings

temperature_readings = []

for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    if device_type == "Temperature_Sensor":
        temp_dict = {
            "timestamp": timestamp,
            "device_id": device_id,
            "location": location,
            "temperature_celsius": value
        }
        temperature_readings.append(temp_dict)

print("\nTemperature Readings:")
for temp in temperature_readings:
    print(temp)
 #1.3 Create a set named 'unique_locations' containing all unique locations from 'raw_sensor_data'.

# Your code for Task 1.3 here:



# 1.3 Create a set named 'unique_locations' containing all unique locations

unique_locations = set()

for reading in raw_sensor_data:
    unique_locations.add(reading[3])   # reading[3] is the location

print("\nUnique Locations:")
print(unique_locations)
 #1.4 Create a dictionary named 'device_stats' where keys are 'device_type' and values are
#     a tuple: (min_value, max_value) observed for that device type across all readings.
#     Initialize with sensible large/small values.

# Your code for Task 1.4 here:
# 1.4 Create a dictionary named 'device_stats'

device_stats = {}

# Initialize min and max values
for device in DEVICE_TYPES:
    device_stats[device] = (float('inf'), float('-inf'))

# Update min and max values
for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    min_value, max_value = device_stats[device_type]

    if value < min_value:
        min_value = value

    if value > max_value:
        max_value = value

    device_stats[device_type] = (min_value, max_value)

print("\nDevice Statistics:")
for device, stats in device_stats.items():
    print(device, ":", stats)
# 1.5.1 List Slicing

# Extract elements from 10th to 20th (inclusive)
# Python indexing starts from 0, so 10th element = index 9 and 20th element = index 19
sliced_readings_1 = raw_sensor_data[9:20]

# Extract every 5th reading starting from the beginning
sliced_readings_2 = raw_sensor_data[::5]

print("\nReadings from 10th to 20th:")
for reading in sliced_readings_1:
    print(reading)

print("\nEvery 5th Reading:")
for reading in sliced_readings_2:
    print(reading)
print("\nEvery 5th Reading:")
for reading in sliced_readings_2:
    print(reading)
    # 1.5.2 String Slicing: Extract the substring "Programming" from 'sample_string'.
#       Store the result in 'substring_1'.
#       Then, extract the substring "nohtyP" (the reverse of "Python") from 'sample_string' using slicing.
#       Store the result in 'substring_2'.

# Your code for Task 1.5.2 here:
sample_string = "PythonProgrammingIsFun"
# 1.5.2 String Slicing

# Extract "Programming"
substring_1 = sample_string[6:17]

# Extract "nohtyP" (reverse of "Python")
substring_2 = sample_string[5::-1]

print("\nSubstring 1:", substring_1)
print("Substring 2:", substring_2)

import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}
raw_sensor_data = []

for i in range(1, 101):
    timestamp_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    device_id = f"DEV{i:03d}"

    device_type = random.choice(DEVICE_TYPES)

    location = random.choice(LOCATIONS)

    low, high = READING_RANGES[device_type]
    value = round(random.uniform(low, high), 2)

    raw_sensor_data.append((timestamp_str, device_id, device_type, location, value))


# 1.2 From 'raw_sensor_data', create a list named 'temperature_readings' containing only the readings
#     where 'device_type' is 'Temperature_Sensor'.
#     Each item in 'temperature_readings' should be a dictionary with keys:
#     'timestamp', 'device_id', 'location', 'temperature_celsius'.
# 1.2 Create a list of temperature sensor readings

temperature_readings = []

for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    if device_type == "Temperature_Sensor":
        temp_dict = {
            "timestamp": timestamp,
            "device_id": device_id,
            "location": location,
            "temperature_celsius": value
        }
        temperature_readings.append(temp_dict)

print("\nTemperature Readings:")
for temp in temperature_readings:
    print(temp)
 #1.3 Create a set named 'unique_locations' containing all unique locations from 'raw_sensor_data'.

# Your code for Task 1.3 here:



# 1.3 Create a set named 'unique_locations' containing all unique locations

unique_locations = set()

for reading in raw_sensor_data:
    unique_locations.add(reading[3])   # reading[3] is the location

print("\nUnique Locations:")
print(unique_locations)
 #1.4 Create a dictionary named 'device_stats' where keys are 'device_type' and values are
#     a tuple: (min_value, max_value) observed for that device type across all readings.
#     Initialize with sensible large/small values.

# Your code for Task 1.4 here:
# 1.4 Create a dictionary named 'device_stats'

device_stats = {}

# Initialize min and max values
for device in DEVICE_TYPES:
    device_stats[device] = (float('inf'), float('-inf'))

# Update min and max values
for reading in raw_sensor_data:
    timestamp, device_id, device_type, location, value = reading

    min_value, max_value = device_stats[device_type]

    if value < min_value:
        min_value = value

    if value > max_value:
        max_value = value

    device_stats[device_type] = (min_value, max_value)

print("\nDevice Statistics:")
for device, stats in device_stats.items():
    print(device, ":", stats)
# 1.5.1 List Slicing

# Extract elements from 10th to 20th (inclusive)
# Python indexing starts from 0, so 10th element = index 9 and 20th element = index 19
sliced_readings_1 = raw_sensor_data[9:20]

# Extract every 5th reading starting from the beginning
sliced_readings_2 = raw_sensor_data[::5]

print("\nReadings from 10th to 20th:")
for reading in sliced_readings_1:
    print(reading)

print("\nEvery 5th Reading:")
for reading in sliced_readings_2:
    print(reading)
print("\nEvery 5th Reading:")
for reading in sliced_readings_2:
    print(reading)
    # 1.5.2 String Slicing: Extract the substring "Programming" from 'sample_string'.
#       Store the result in 'substring_1'.
#       Then, extract the substring "nohtyP" (the reverse of "Python") from 'sample_string' using slicing.
#       Store the result in 'substring_2'.

# Your code for Task 1.5.2 here:
sample_string = "PythonProgrammingIsFun"
# 1.5.2 String Slicing

# Extract "Programming"
substring_1 = sample_string[6:17]

# Extract "nohtyP" (reverse of "Python")
substring_2 = sample_string[5::-1]

print("\nSubstring 1:", substring_1)
print("Substring 2:", substring_2)
# 1.5.3 Mixed Slicing: Access the 'device_type' of the 5th reading in 'raw_sensor_data' using indexing.
#       Store it in 'fifth_reading_device_type'.
#       Then, from 'fifth_reading_device_type', extract the last 6 characters (e.g., 'Sensor' from 'Temperature_Sensor').
#       Store it in 'device_type_suffix'.

# Your code for Task 1.5.3 here:

# 1.5.3 Mixed Slicing

# Get the device_type of the 5th reading
fifth_reading_device_type = raw_sensor_data[4][2]

# Extract the last 6 characters
device_type_suffix = fifth_reading_device_type[-6:]

print("\n5th Reading Device Type:", fifth_reading_device_type)
print("Device Type Suffix:", device_type_suffix)

# 2.1 Function to get readings by location

def get_readings_by_location(readings_list, target_location):
    result = []

    for reading in readings_list:
        if reading[3] == target_location:   # reading[3] is the location
            result.append(reading)

    return result

# Example usage
lab1_readings = get_readings_by_location(raw_sensor_data, "Lab1")

print("\nReadings from Lab1:")
for reading in lab1_readings:
    print(reading)



# 2.1 Function to get readings by location

def get_readings_by_location(readings_list, target_location):
    result = []

    for reading in readings_list:
        if reading[3] == target_location:   # reading[3] is the location
            result.append(reading)

    return result

# Example usage
lab1_readings = get_readings_by_location(raw_sensor_data, "Lab1")

print("\nReadings from Lab1:")
for reading in lab1_readings:
    print(reading)
    # 2.2 Write a function `calculate_average_temperature(temp_data_list)`
#     that takes the 'temperature_readings' list (list of dictionaries).
#     It should calculate and return the average temperature. Return 0.0 if the list is empty.

# Your code for Task 2.2 here:

# 2.2 Function to calculate average temperature

def calculate_average_temperature(temp_data_list):
    if len(temp_data_list) == 0:
        return 0.0

    total = 0

    for reading in temp_data_list:
        total += reading["temperature_celsius"]

    average = total / len(temp_data_list)
    return average

# Example usage
avg_temp = calculate_average_temperature(temperature_readings)

print("\nAverage Temperature:", round(avg_temp, 2), "°C")