# -*- coding: utf-8 -*-
"""week3_linear_algebra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vKvT59otC5N0ntdm2ciJCgvs5E-qMJUz
"""



import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt

np.set_printoptions(precision=3, suppress=True)
np.random.seed(42)
print('Setup complete. NumPy', np.__version__)



scalar = np.array(5)
vector = np.array([2, 5, 1])
matrix = np.array([[1, 2], [3, 4]])
tensor = np.ones((3, 2, 2))
for name, arr in [('scalar', scalar), ('vector', vector),
                  ('matrix', matrix), ('tensor', tensor)]:
    print(f'{name:7s} ndim={arr.ndim}  shape={arr.shape}')

A = np.arange(6).reshape(2, 3)
B = np.ones((2, 3), dtype=int)

print('A:\n', A)
print('A + B (element-wise add):\n', A + B)
print('A.T  (transpose -> shape', A.T.shape, '):\n', A.T)
print('A.reshape(3, 2):\n', A.reshape(3, 2))
print('A.flatten():', A.flatten())

T = np.arange(12).reshape(3, 4)
print('T:\n', T)

a = np.array([1, 2, 3])
b = np.array([4, 0, 1])
print('a . b  (dot)   :', np.dot(a, b))
print('a x b  (cross) :', np.cross(a, b))

print('L2 norm  ||a||_2 :', la.norm(a))
print('L1 norm  ||a||_1 :', la.norm(a, 1))
print('Linf norm        :', la.norm(a, np.inf))
def cosine(u, v):
    return np.dot(u, v) / (la.norm(u) * la.norm(v))

print('cosine(a, b)     :', round(cosine(a, b), 3))



square = np.array([[0, 1, 1, 0],
                   [0, 0, 1, 1]], dtype=float)

S = np.array([[1.5, 0.0],
              [0.0, 0.5]])

t = np.radians(30)
R = np.array([[np.cos(t), -np.sin(t)],
              [np.sin(t),  np.cos(t)]])

scaled  = S @ square
rotated = R @ square
print('Rotated corners:\n', rotated)



def close_loop(pts):
    return np.hstack([pts, pts[:, :1]])

fig, ax = plt.subplots(figsize=(5, 5))
ax.plot(*close_loop(square),  marker='o', label='original')
ax.plot(*close_loop(scaled),  marker='o', label='scaled')
ax.plot(*close_loop(rotated), marker='o', label='rotated 30 deg')
ax.axhline(0, color='gray', lw=0.5); ax.axvline(0, color='gray', lw=0.5)
ax.set_aspect('equal'); ax.legend(); ax.set_title('Linear transformations')
plt.show()

C = np.array([[4., 1.],
              [2., 3.]])



A = np.array([[ 2.,  1., -1.],
              [-3., -1.,  2.],
              [-2.,  1.,  2.]])
b = np.array([8., -11., -3.])

x = la.solve(A, b)
print('Solution x:', x)
print('Rank of A :', la.matrix_rank(A))
print('Full rank -> a unique solution exists')